sudo: false
language: node_js
node_js:
  - '8'
before_install:
  - openssl aes-256-cbc -K $encrypted_24e8c62a750c_key -iv $encrypted_24e8c62a750c_iv
    -in id_rsa.enc -out ~\/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
install:
  - npm install
script:
  - npm run build
after_success:
  - rm -rf .git/ .idea/ # 删除无关的文件夹
  - npm prune --production # 删除devDependencies
  - npm run build-release # 压缩打包

before_deploy:
  - cp *-release.tgz ~
  - export PACKAGE_PATH=$(readlink -f ~/*-release.tgz)
  - echo $PACKAGE_PATH

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_TOKEN
  file: $PACKAGE_PATH
  skip_cleanup: true
  on:
    repo: homelajiang/aflow-web
    tags: true
    branch: master

after_deploy:
  - scp $PACKAGE_PATH ${SERVER_SSH}:~/release.tgz # 复制到生产环境
  - ssh ${SERVER_SSH} 'mkdir -p release && cd release && rm -rf * && cd .. && tar -zxvf release.tgz -C release' # 解压
  - ssh ${SERVER_SSH} 'cd release && npm stop && npm start'

addons:
  ssh_known_hosts: ${SERVER_HOST}
