sudo: false
language: node_js
node_js:
  - '8'

# 字段用来指定安装脚本。
install:
  - npm install --only=dev
  - npm run build
  - rm -rf node_modules/
  - npm install --production
  - tar -zcvf ../release.taz .

# 字段用来指定构建或测试脚本。
script:
  - npm -v
#after_script:
#  - npminstall codecov && codecov
